[tool.isort]
# for details see
# http://docs.plone.org/develop/styleguide/python.html#grouping-and-sorting
force_alphabetical_sort = True
force_single_line = True
known_future_library = "future,pies"
lines_after_imports = 2
line_length = 88
not_skip = __init__.py

